apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fy0ptyoks-nodejs
  janus-idp.io/tekton: fy0ptyoks-nodejs
  backstage.io/kubernetes-id: fy0ptyoks-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fy0ptyoks-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
